# Generated by Django 2.2.6 on 2020-06-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0002_auto_20200610_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='facebook_ac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='google_ac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='instagram_ac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='linkedin_ac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='whatshapp_ac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
