# Generated by Django 2.2.6 on 2020-06-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0003_auto_20200610_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='user_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
