# Generated by Django 2.2.6 on 2020-06-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0004_userdatabase_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
