# Generated by Django 2.2.6 on 2020-06-14 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0007_company_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_model',
            old_name='title',
            new_name='company_title',
        ),
        migrations.AddField(
            model_name='company_model',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company_model',
            name='linkedin_ac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_model',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_model',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_model',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
