# Generated by Django 2.2.6 on 2020-06-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0008_auto_20200614_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_model',
            options={'verbose_name': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='connections',
            options={'verbose_name': 'Connections'},
        ),
    ]
