# Generated by Django 2.2.6 on 2020-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0009_auto_20200614_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_model',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='connections',
            options={'verbose_name': 'Connection', 'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterModelOptions(
            name='userdatabase',
            options={'verbose_name': 'UserData', 'verbose_name_plural': 'UserDataBase'},
        ),
        migrations.AlterField(
            model_name='company_model',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
