# Generated by Django 2.2.6 on 2020-06-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0010_auto_20200614_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_model',
            name='category',
            field=models.CharField(blank=True, default='Information Technology', max_length=150, null=True),
        ),
    ]
