# Generated by Django 2.2.6 on 2020-06-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0013_auto_20200615_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_model',
            name='is_verified',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10, null=True),
        ),
    ]
