# Generated by Django 2.2.6 on 2020-06-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0014_auto_20200615_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_model',
            old_name='address',
            new_name='map',
        ),
    ]
