# Generated by Django 2.2.6 on 2020-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0018_auto_20200617_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('query', models.TextField(max_length=500)),
            ],
        ),
    ]
