# Generated by Django 2.2.6 on 2020-06-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0019_queries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('query', models.TextField(max_length=500)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Connect.Company_Model')),
            ],
        ),
    ]
